export const INVENTORY_TRANSACTION_TYPES = {
  DEPT_EXPIRED_RETURN: 'DEPT-EXPIRED-RETURN',
  DEPT_GENERAL_RETURN: 'DEPT-GENERAL-RETURN',
  DEPT_OUT: 'DEPT-OUT',
  DISPOSED: 'DISPOSED',
  IN: 'IN',
  RESALE: 'RESALE',
  SUPPLIER_RETURN: 'SUPPLIER-RETURN'
} as const;

export type InventoryTransactionTypeCode = typeof INVENTORY_TRANSACTION_TYPES[keyof typeof INVENTORY_TRANSACTION_TYPES];

// Transaction types that require department selection
export const DEPARTMENT_REQUIRED_TRANSACTION_TYPES = [
  INVENTORY_TRANSACTION_TYPES.DEPT_OUT,
  INVENTORY_TRANSACTION_TYPES.DEPT_EXPIRED_RETURN,
  INVENTORY_TRANSACTION_TYPES.DEPT_GENERAL_RETURN
] as const;

// Transaction types that decrease inventory quantity (outgoing)
export const OUTGOING_TRANSACTION_TYPES = [
  INVENTORY_TRANSACTION_TYPES.DEPT_OUT,
  INVENTORY_TRANSACTION_TYPES.DEPT_EXPIRED_RETURN,
  INVENTORY_TRANSACTION_TYPES.DEPT_GENERAL_RETURN,
  INVENTORY_TRANSACTION_TYPES.DISPOSED,
  INVENTORY_TRANSACTION_TYPES.RESALE,
  INVENTORY_TRANSACTION_TYPES.SUPPLIER_RETURN
] as const;
